FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY ["Mediscreen.Frontend/Mediscreen.Frontend.csproj", "Mediscreen.Frontend/"]
RUN dotnet restore "Mediscreen.Frontend/Mediscreen.Frontend.csproj"

COPY . .
WORKDIR "/src/Mediscreen.Frontend"

RUN dotnet publish \
    "Mediscreen.Frontend.csproj" \
    -c Release \
    -o /app/publish \
    /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final
WORKDIR /app

ENV ASPNETCORE_HTTP_PORTS=8080
EXPOSE 8080

COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "Mediscreen.Frontend.dll"]